# Generated by Django 5.0.1 on 2024-05-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Booking_date', models.DateField()),
                ('Booked_on', models.DateField(auto_now=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
            ],
        ),
    ]
