# Generated by Django 5.0.1 on 2024-05-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_patient_email_id_remove_patient_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
