# Generated by Django 5.0.1 on 2024-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_staff_receptionist_pharmacist_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
