# Generated by Django 5.0.1 on 2024-06-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_alter_staff_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
