# Generated by Django 5.0.1 on 2024-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_remove_pharmacist_staff_remove_receptionist_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('nurse', 'Nurse'), ('pharmacist', 'pharmacist')], max_length=50)),
            ],
        ),
    ]
