# Generated by Django 5.0.1 on 2024-06-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
