# Generated by Django 5.0.1 on 2024-06-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_pharmacist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacist',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='phone_number',
        ),
    ]
